# import pandas

In [1]:
import pandas as pd

# 🔰 1️⃣ Data Import / Export
- `pd.read_csv()`
- `pd.read_excel()`
- `pd.read_json()`

## Save Data Format
- `df.to_csv()`
- `df.to_excel()`

In [4]:
df = pd.read_excel(r"C:\Users\Anish Kumar\Downloads\Merge_Append_PowerBI_Data.xlsx")
df

     CustomerID   CustomerName Region SignupDate
0             1     Customer_1   East 2021-05-16
1             2     Customer_2   West 2022-08-16
2             3     Customer_3  North 2023-03-14
3             4     Customer_4   East 2023-05-09
4             5     Customer_5   East 2022-07-17
..          ...            ...    ...        ...
995         996   Customer_996  North 2023-02-10
996         997   Customer_997  North 2023-06-10
997         998   Customer_998   West 2020-01-17
998         999   Customer_999   West 2020-12-25
999        1000  Customer_1000   East 2023-05-31

[1000 rows x 4 columns]

In [5]:
df.head()

   CustomerID CustomerName Region SignupDate
0           1   Customer_1   East 2021-05-16
1           2   Customer_2   West 2022-08-16
2           3   Customer_3  North 2023-03-14
3           4   Customer_4   East 2023-05-09
4           5   Customer_5   East 2022-07-17

In [6]:
df.columns

Index(['CustomerID', 'CustomerName', 'Region', 'SignupDate'], dtype='str')

# 🔰 2️⃣ Indexing & Selection 
- df.loc[] → Label based
- df.iloc[] → Index based
- Boolean indexing
- Slicing

# 🔰 3️⃣ Data Cleaning 
- drop()
- rename()
- replace()
- duplicated()
- drop_duplicates()
- astype()

# 🔰 4️⃣ Aggregation & Statistics
- mean()
- sum()
- count()
- min()
- max()
- value_counts()
- corr()

# 🔰 5️⃣ GroupBy & Pivot Table
- groupby()
- pivot_table()- 
- crosstab()

# 🔰 6️⃣ Merge & Join (🔥 Very Important)
- merge()
- join()
- concat()

# 🔰 7️⃣ Date & Time Handling
- pd.to_datetime()
- .dt.year
- .dt.month
- .dt.day

# 🔰 8️⃣ Apply & Lambda
`df["Grade"] = df["Marks"].apply(lambda x: "Pass" if x > 40 else "Fail")`